web/openelm/management/urls.py
from django.conf.urls.defaults import *


__copyright__ = "Copyright 2011-2014 Red Robot Studios Ltd.  All rights reserved."
__license__ = "MIT http://opensource.org/licenses/MIT"


urlpatterns = patterns('',
    url(r'^$', 'management.views.index', name='management_index'),
    url(r'^reports/$', 'management.views.records', name='management_reports'),
    url(r'^record/(?P<record_id>\w+)/$', 'management.views.record_detail', name='management_record_detail'),
    url(r'^record/(?P<record_id>\w+)/edit/$', 'management.views.edit_record', name='management_edit_record'),
)

web/openelm/urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from django.contrib import admin


__copyright__ = "Copyright 2011-2014 Red Robot Studios Ltd."
__license__ = "MIT http://opensource.org/licenses/MIT"


admin.autodiscover()


urlpatterns = patterns('',
    (r'', include('openelm.public.urls')),
    (r'accounts/', include('openelm.accounts.urls')),
    (r'management/', include('openelm.management.urls')),
    (r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    # Serve media files through dev server.
    urlpatterns += patterns('',
        (r'^media/(v\d*/)?(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    )

web/openelm/record/forms.py
import os

from django import forms
from couchdbkit.ext.django.forms  import DocumentForm

from record.documents import Record
from record.utils import get_review_zone_for_coordinates


__copyright__ = "Copyright 2011-2014 Red Robot Studios Ltd."
__license__ = "MIT http://opensource.org/licenses/MIT"


class AddRecordForm(DocumentForm):
    
    MAX_UPLOAD_SIZE = 1024
    ACCEPTED_FILETYPES = ('.jpeg', '.jpg')
    STATUS_CHOICES = (
        ('healthy', 'Healthy'),
        ('inspection-required', 'Inspection Required'))
    
    username = forms.CharField(required=False,
                                label=u'Your username',
                                widget=forms.TextInput(attrs={'placeholder': 'Optional', 'autocomplete': 'on'}),
                                 help_text=u"Use something unique as your username so you can see your contribution to the project")
    photo = forms.ImageField(required=True, help_text=u'Maximum size of 2MB. JPG only.')
    status = forms.ChoiceField(required=True, choices=STATUS_CHOICES)
    location_lat = forms.CharField(required=False, widget=forms.HiddenInput())
    location_lng = forms.CharField(required=False, widget=forms.HiddenInput())
    street_address = forms.CharField(required=False, 
                                        widget=forms.TextInput(attrs={
                                                'placeholder': 'Drag the marker to set the location',
                                                'disabled': 'disabled'}))
    notes = forms.CharField(required=False, widget=forms.Textarea(attrs={'placeholder': 'Optional'}))
    #simple honeypot field
    extent = forms.CharField(required=False, widget=forms.HiddenInput())
    
    class Meta:
        document = Record
        exclude = ('photo',)
    
    def clean_photo(self):
        photo = self.cleaned_data['photo']
        if photo:
            if (photo.size / 2048) > self.MAX_UPLOAD_SIZE:
                raise forms.ValidationError(u'The image is too large to be uploaded. It must be less than 2MB.')
            name, extension = os.path.splitext(photo.name)
            if extension.lower() not in self.ACCEPTED_FILETYPES:
                raise forms.ValidationError(u'We do not support the %s filetype. Please convert your photo ' \
                                            'to a jpeg and try again.' % extension)
        return photo
    
    def clean_extent(self):
        extent = self.cleaned_data['extent']
        if extent:
            raise forms.ValidationError(u'Validation failed.')
        return extent
    
    def clean(self):
        location_lat = self.cleaned_data['location_lat']
        location_lng = self.cleaned_data['location_lng']
        if not location_lat or not location_lng:
            raise forms.ValidationError(u'Please use the map to choose the location ' \
                                        'and edit the street address if necessary')
        review_zone = get_review_zone_for_coordinates(location_lat, location_lng)
        if review_zone is None:
            raise forms.ValidationError(u'This location is outside of the areas supported by this project')
        return self.cleaned_data


class ManageRecordForm(AddRecordForm):
    
    STATUS_CHOICES = (
        ('healthy', 'Healthy'),
        ('invalid', 'Invalid'),
        ('inspection-required', 'Inspection Required'),
        ('confirmed', 'Confirmed Disease'),
        ('felled', 'Felled'),)
    
    username = forms.CharField(required=False,
                                label=u'Submitter\'s Username',
                                widget=forms.TextInput(attrs={'placeholder': 'Optional', 'autocomplete': 'on'}))
    review_notes = forms.CharField(required=False, widget=forms.Textarea(attrs={'placeholder': 'Your review notes'}))
    status = forms.ChoiceField(required=False, choices=STATUS_CHOICES)
    photo = forms.ImageField(required=False)
    
    class Meta:
        document = Record
        exclude = ('photo',)

web/openelm/management/views.py
import datetime

from django.shortcuts import render_to_response
from django.template import RequestContext
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.core import urlresolvers
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_control

from record.documents import Record
from record.forms import ManageRecordForm
from record.utils import get_couch_document_or_404, get_photo_url_for_record
from record import tasks


__copyright__ = "Copyright 2011-2014 Red Robot Studios Ltd."
__license__ = "MIT http://opensource.org/licenses/MIT"


RECORDS_PER_PAGE = 20


@login_required
@cache_control(private=True)
def index(request):
    profile = request.user.get_profile()
    records = Record.view('record/unreviewed', startkey=profile.review_zone)
    return render_to_response('management/index.html',
                {'records': records,
                'current_page': 'management'},
                context_instance=RequestContext(request))

@login_required
@cache_control(private=True)
def records(request):
    next = ''
    profile = request.user.get_profile()
    kwargs = {
        'descending': True,
        'limit': RECORDS_PER_PAGE + 1,
        'startkey': profile.review_zone
    }
    if 'n' in request.GET:
        kwargs['startkey'] = request.GET['n']
    records = list(Record.get_db().view('record/all', **kwargs))
    if len(records) > RECORDS_PER_PAGE:
        next = records[-1]['key']
    for record in records:
        record['value']['creation_date'] = convert_datetime_string(record['value']['creation_date'])
        record['value']['review_date'] = convert_datetime_string(record['value'].get('review_date'))
    return render_to_response('management/records.html',
                {'records': records[:-1],
                'next': next,
                'querystring': request.META['QUERY_STRING'],
                'current_page': 'management'},
                context_instance=RequestContext(request))

@login_required
@cache_control(private=True)
def record_detail(request, record_id):
    record = get_record(request.user, record_id)
    photo_url = get_photo_url_for_record(record)
    return render_to_response('management/record_detail.html',
                {'record': record,
                'photo_url': photo_url,
                'current_page': 'management'},
                context_instance=RequestContext(request))

@login_required
@cache_control(private=True)
def edit_record(request, record_id):
    record = get_record(request.user, record_id)
    photo_url = get_photo_url_for_record(record)
    if request.method == 'POST':
        if 'delete' in request.POST:
            record.delete()
            tasks.delete_photos_for_record_id.delay(record_id)
        elif 'approve' in request.POST:
            record.review_date = datetime.datetime.utcnow()
            record.reviewed_by = request.user.username
            record.save()
        else:            
            form = ManageRecordForm(request.POST, instance=record)
            if form.is_valid():
                record = form.save(commit=False)
                record.review_date = datetime.datetime.utcnow()
                record.reviewed_by = request.user.username
                del record.extent
                #remove as we're adding lat/lng as geometry
                del record.location_lat
                del record.location_lng
                record.geometry = {
                    'type': 'Point',
                    'coordinates': [float(form.cleaned_data['location_lat']),
                                    float(form.cleaned_data['location_lng'])]
                }
                record.save()
        return HttpResponseRedirect(urlresolvers.reverse('management_index'))
    else:
        initial = {
            'location_lat': record.geometry['coordinates'][0],
            'location_lng': record.geometry['coordinates'][1]
        }
        form = ManageRecordForm(instance=record, initial=initial)
    return render_to_response('management/edit_record.html',
                {'form': form,
                'photo_url': photo_url,
                'current_page': 'management'},
                context_instance=RequestContext(request))


def convert_datetime_string(value):
    if value:
        value = value.split('.', 1)[0] # strip out microseconds
        value = value[0:19] # remove timezone
        return datetime.datetime.strptime(value, '%Y-%m-%dT%H:%M:%S')
    return ''

def get_record(user, record_id):
    profile = user.get_profile()
    record = get_couch_document_or_404(Record, record_id)
    if record.review_zone != profile.review_zone:
        raise Http404(u'Record not found')
    return record

web/openelm/templates/management/edit_record.html
{% extends 'base.html' %}
{% block title %}Editing Record {{ block.super }}{% endblock %}
{% block main_content %}
<div id="content_wrapper" class="clearfix">
    <div class="grid_12 alpha">
        <h2>Edit Record</h2>
        <form class="grid_8 generic_form rounded_12" method="post" enctype="multipart/form-data" action=".">
            <fieldset class="generic">
                <legend class="step">Record Location</legend>
                <div class="field grid_7 w_578 clearfix">
                    <div class="content_map_canvas"></div>
                </div>
                <div class="field grid_7 w_578">
                    {{ form.street_address.label_tag }}{{ form.street_address }}{{ form.street_address.errors }}
                </div>
            </fieldset>
            <fieldset class="generic">
                <legend class="step">Record Details</legend>
                <div class="field grid_4">
                    {{ form.username.label_tag }}{{ form.username }}{{ form.username.errors }}
                </div>
                <div class="field grid_7 w_578">
                    {{ form.notes.label_tag }}{{ form.notes }}{{ form.notes.errors }}
                </div>
            </fieldset>
            <fieldset class="generic">
                <legend class="step">Review Details</legend>
                <div class="field grid_7 w_578">
                    {{ form.review_notes.label_tag }}{{ form.review_notes }}{{ form.review_notes.errors }}
                </div>
                <div class="field grid_4">
                    {{ form.status.label_tag }}{{ form.status }}{{ form.status.errors }}
                </div>
                <div class="field grid_7 w_578 omega">
                    {{ form.location_lat }}
                    {{ form.location_lng }}
                    {{ form.extent }}
                    <a class="back_nav cancel mock_button" href="javascript:void(0);">Cancel</a>
                    <input class="submit" type="submit" value="Save">
                    <input class="submit flr delete" id="id_delete" type="submit" name="delete" value="Delete">
                    {% csrf_token %}
                </div>
            </fieldset>
        </form>
    </div>
</div>
{% endblock main_content %}
{% block end_body_scripts %}
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
<script type="text/javascript">
    $(document).ready(function() {
        $('#id_street_address').removeAttr('disabled');
        var default_location = new google.maps.LatLng({{ form.instance.geometry.coordinates.0 }}, {{ form.instance.geometry.coordinates.1 }});
        var info_window = new google.maps.InfoWindow();
        var map_options = {
            zoom: 17,
            center: default_location,
            mapTypeId: google.maps.MapTypeId.HYBRID
        }
        var map = new google.maps.Map($('div.content_map_canvas')[0], map_options);
        var marker = new google.maps.Marker({
            map: map,
            draggable: true,
            animation: google.maps.Animation.DROP,
            position: default_location
        });
        google.maps.event.addListener(marker, 'dragend', function(location) {
            var ll = location.latLng;
            $('#id_location_lat').val(ll.lat());
            $('#id_location_lng').val(ll.lng());
            marker.setPosition(ll);
            new google.maps.Geocoder().geocode({'latLng': ll}, function(results, status) {
                if (status == google.maps.GeocoderStatus.OK) {
                    if(results[0]) {
                        location_address = results
                        info_window.setContent(location_address[0].formatted_address);
                        $('#id_street_address').val(location_address[0].formatted_address);
                        google.maps.event.addListener(marker, 'click', function(location) {
                            info_window.open(map, marker);
                        });
                    }
                }
            });
        });
    });
</script>

{% endblock %}

web/openelm/templates/management/index.html
{% extends 'base.html' %}{% load record_tags %}
{% block title %}Management {{ block.super }}{% endblock %}
{% block main_content %}
<div id="content_wrapper" class="clearfix">
    <div class="grid_12 alpha">
        <ul class="tabs">
            <li><strong>Unreviewed Reports</strong></li>
            <li><a href="{% url management_reports %}">All Reports</a></li>
        </ul>
        <table cellspacing="0" class="detail_table">
            <thead>
                <tr>
                    <th class="w_5">&nbsp;</th>
                    <th>Address</th>
                    <th>Status</th>
                    <th>Submitted on</th>
                </tr>
            </thead>
            <tbody>
                {% for record in records %}
                <tr>
                    <td{% if not record.review_date %} class="new"{% endif %}></td>
                    <td><a href="{% url management_record_detail record_id=record.get_id %}">{{ record.street_address }}</a></td>
                    <td>{{ record.status|strip_punctuation|title }}</td>
                    <td>{{ record.creation_date }}</td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="4"><h5 class="empty">No Records</h5></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock main_content %}

web/openelm/templates/management/record_detail.html
{% extends 'base.html' %}{% load record_tags %}
{% block title %}Record Details {{ block.super }}{% endblock %}
{% block main_content %}
<div id="content_wrapper" class="clearfix">
    <div class="grid_12 alpha">
        <h2>Record Details</h2>
        <div id="record_detail_wrap" class="grid_8 alpha">
            <div class="content_map_canvas"></div>
            <dl class="detail_list">
                <dt>Submitted by:</dt>
                <dd>{{ record.username }}</dd>
                <dt>Submitted on:</dt>
                <dd>{{ record.creation_date }}</dd>
                <dt>Status:</dt>
                <dd>{{ record.status|strip_punctuation|title }}</dd>
                <dt>Address:</dt>
                <dd>{{ record.street_address }}</dd>
                {% if record.notes %}
                <dt>Notes:</dt>
                <dd>{{ record.notes|linebreaks }}</dd>
                {% endif %}
                <dt>Photo:</dt>
                <dd><a href="{{ record.photo_url }}" target="_blank"><img src="{{ record.thumbnail_url }}" width="600"></a></dd>
                {% if record.review_date %}
                <dt>Reviewed on:</dt>
                <dd>{{ record.review_date }}</dd>
                <dt>Reviewed by:</dt>
                <dd>{{ record.reviewed_by }}</dd>
                {% if record.review_notes %}
                <dt>Review notes:</dt>
                <dd>{{ record.review_notes|linebreaks }}</dd>
                {% endif %}
                {% endif %}
            </dl>
            <form class="grid_8 generic_form" method="post" action="{% url management_edit_record record_id=record.get_id %}">
                <div class="field grid_7 w_578 omega">
                    <input class="submit delete" id="id_delete" type="submit" name="delete" value="Delete">
                    <a class="mock_button" href="{% url management_edit_record record_id=record.get_id %}">Edit</a>
                    {% if not record.review_date %}
                    <input class="submit" id="id_approve" type="submit" name="approve" value="Approve">
                    {% endif %}
                    {% csrf_token %}
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock main_content %}
{% block end_body_scripts %}
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
<script type="text/javascript">
    $(document).ready(function() {
        var default_location = new google.maps.LatLng({{ record.geometry.coordinates.0 }}, {{ record.geometry.coordinates.1 }});
        var info_window = new google.maps.InfoWindow();
        var map_options = {
            zoom: 17,
            center: default_location,
            mapTypeId: google.maps.MapTypeId.HYBRID
        }
        var map = new google.maps.Map($('div.content_map_canvas')[0], map_options);
        var marker = new google.maps.Marker({
            map: map,
            draggable: false,
            animation: google.maps.Animation.DROP,
            position: default_location
        });
        google.maps.event.addListener(marker, 'click', function(location) {
            info_window.open(map, marker);
        });
    });
</script>
{% endblock %}

web/openelm/templates/management/records.html
{% extends 'base.html' %}{% load record_tags %}
{% block title %}Management {{ block.super }}{% endblock %}
{% block main_content %}
<div id="content_wrapper" class="clearfix">
    <div class="grid_12 alpha">
        <ul class="tabs">
            <li><a href="{% url management_index %}">Unreviewed Reports</a></li>
            <li><strong>All Reports</strong></li>
        </ul>
        <table cellspacing="0" class="detail_table">
            <thead>
                <tr>
                    <th class="w_5">&nbsp;</th>
                    <th>Address</th>
                    <th>Status</th>
                    <th>Submitted on</th>
                    <th>Reviewed on</th>
                </tr>
            </thead>
            <tbody>
                {% for record in records %}
                <tr>
                    <td{% if not record.value.review_date %} class="new"{% endif %}>&nbsp;</td>
                    <td><a href="{% url management_record_detail record_id=record.id %}">{{ record.value.street_address }}</a></td>
                    <td>{{ record.value.status|strip_punctuation|title }}</td>
                    <td>{{ record.value.creation_date }}</td>
                    <td>{{ record.value.review_date }}</td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="4"><h5 class="empty">No Records</h5></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% if querystring %}<a class="back_nav grid_2" href="javascript:void(0);">&laquo; Previous</a>&nbsp;{% endif %}
        {% if next %}<a class="grid_1 fr" href="{% url management_reports %}?n={{ next }}">Next &raquo;</a>{% endif %}
        <a></a>
    </div>
</div>
{% endblock main_content %}